import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,appendFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {CodexDesktopObserver,desktopEvent} from '../core/codex-desktop.mjs';
import {applyEvent,agentCards} from '../plugins/agents/state.mjs';
const line=(type,payload,time=Date.now())=>JSON.stringify({timestamp:new Date(time).toISOString(),type,payload})+'\n';
async function fixture(t){const home=mkdtempSync(join(tmpdir(),'deck-desktop-'));const codex=join(home,'.codex');mkdirSync(join(codex,'sessions'),{recursive:true});const db=new DatabaseSync(join(codex,'state_5.sqlite'));db.exec('CREATE TABLE threads(id TEXT,rollout_path TEXT,cwd TEXT,source TEXT,archived INTEGER,updated_at INTEGER)');const values=new Map();const emitted=[],sessions={};let removed=0;const observer=new CodexDesktopObserver({home,env:{},appPaths:[home],store:{get:(k,x,f)=>values.get(x)??f,set:(k,x,v)=>values.set(x,v)},onEvent:async e=>{emitted.push(e);applyEvent(sessions,e);},onRemove:async()=>{removed++;for(const [id,s] of Object.entries(sessions))if(s.client==='desktop')delete sessions[id];}});await observer.refresh();t.after(async()=>{await observer.close();db.close();rmSync(home,{recursive:true,force:true});});
 const add=(id,origin='Codex Desktop',source='vscode',extra='')=>{const path=join(codex,'sessions',id+'.jsonl');writeFileSync(path,line('session_meta',{id,originator:origin,source,cwd:'/project',base_instructions:'PRIVATE-INSTRUCTIONS'})+extra);db.prepare('INSERT INTO threads VALUES(?,?,?,?,0,?)').run(id,path,'/project',source,Math.floor(Date.now()/1000));return path;};return {observer,add,emitted,sessions,removed:()=>removed,db,home};}
test('desktop session discovery excludes IDE and CLI, strips conversation content, and follows turns',async t=>{
 const {observer,add,emitted,sessions}=await fixture(t);const path=add('desktop','Codex Desktop','vscode',line('event_msg',{type:'task_started',turn_id:'t1'})+line('response_item',{type:'function_call',name:'read_file',arguments:'PRIVATE-PROMPT'}));add('ide','codex_vscode','vscode',line('event_msg',{type:'task_started'}));add('cli','codex_cli_rs','cli',line('event_msg',{type:'task_started'}));await observer.change('install');assert.equal(agentCards(sessions).length,1);assert.equal(agentCards(sessions)[0].subtitle,'Codex');assert.equal(agentCards(sessions)[0].status,'running');assert.equal(JSON.stringify(emitted).includes('PRIVATE'),false);
 appendFileSync(path,line('event_msg',{type:'task_complete',turn_id:'t1',last_agent_message:'PRIVATE-ANSWER'}));await observer.tick();assert.equal(agentCards(sessions)[0].status,'completed');appendFileSync(path,line('response_item',{type:'custom_tool_call_output',output:'PRIVATE-OUTPUT'}));await observer.tick();assert.equal(agentCards(sessions)[0].status,'completed');assert.equal(JSON.stringify(emitted).includes('PRIVATE'),false);
 appendFileSync(path,line('event_msg',{type:'task_started',turn_id:'t2'})+line('event_msg',{type:'turn_aborted',turn_id:'t2',reason:'interrupted'}));await observer.tick();assert.equal(agentCards(sessions)[0].status,'idle');assert.equal(agentCards(sessions)[0].summary,'本轮已中断');await observer.change('remove');assert.equal(agentCards(sessions).length,0);
});
test('incomplete lines and malformed records do not lose the next event',async t=>{
 const {observer,add,sessions}=await fixture(t);const path=add('partial','Codex Desktop','vscode',line('event_msg',{type:'task_started',turn_id:'t'}));await observer.change('install');const complete=line('event_msg',{type:'task_complete',turn_id:'t'});appendFileSync(path,'{bad}\n'+complete.slice(0,-4));await observer.tick();assert.equal(agentCards(sessions)[0].status,'running');appendFileSync(path,complete.slice(-4));await observer.tick();assert.equal(agentCards(sessions)[0].status,'completed');
});
test('startup replay preserves stale activity instead of inventing live sessions',async t=>{
 const {observer,add,sessions,emitted}=await fixture(t);add('old','Codex Desktop','vscode',line('event_msg',{type:'task_started',turn_id:'t'},Date.now()-600000)+line('event_msg',{type:'task_complete',turn_id:'t'},Date.now()-590000));await observer.change('install');assert.equal(agentCards(sessions)[0].status,'unknown');assert.equal(emitted.filter(e=>e.hook_event_name==='UserPromptSubmit').length,0);
});
test('archived and external paths are excluded; broken schema reports an error without writes',async t=>{
 const {observer,add,db,home,emitted}=await fixture(t);add('archived','Codex Desktop','vscode',line('event_msg',{type:'task_started'}));db.exec("UPDATE threads SET archived=1");const external=join(home,'external.jsonl');writeFileSync(external,line('session_meta',{id:'external',originator:'Codex Desktop',source:'vscode'})+line('event_msg',{type:'task_started'}));db.prepare('INSERT INTO threads VALUES(?,?,?,?,0,?)').run('external',external,'/project','vscode',Math.floor(Date.now()/1000));await observer.change('install');assert.equal(emitted.length,0);db.exec('DROP TABLE threads');await observer.tick();assert.match(observer.status().error,/未修改/);
});
test('asynchronous questions do not falsely report blocking approval; explicit input does',()=>{
 const session={id:'a',cwd:'/project'};const asyncEvent=desktopEvent(JSON.parse(line('response_item',{type:'function_call',name:'request_user_input_async'})),session,'t');assert.equal(asyncEvent.hook_event_name,'PreToolUse');const syncEvent=desktopEvent(JSON.parse(line('response_item',{type:'function_call',name:'functions.request_user_input'})),session,'t');assert.equal(syncEvent.hook_event_name,'PermissionRequest');
});
test('late completion of an older turn does not stop following the current turn',async t=>{
 const {observer,add,sessions}=await fixture(t);const path=add('turns','Codex Desktop','vscode',line('event_msg',{type:'task_started',turn_id:'one'}));await observer.change('install');appendFileSync(path,line('event_msg',{type:'task_started',turn_id:'two'})+line('event_msg',{type:'task_complete',turn_id:'one'})+line('response_item',{type:'function_call',name:'read'}));await observer.tick();assert.equal(agentCards(sessions)[0].status,'running');appendFileSync(path,line('event_msg',{type:'task_complete',turn_id:'two'}));await observer.tick();assert.equal(agentCards(sessions)[0].status,'completed');
});
