import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {parse} from 'acorn';
import {JSDOM} from 'jsdom';
const source=name=>readFileSync(new URL('../web/'+name,import.meta.url),'utf8');
test('phone scripts parse as ES5 and display loads ordinary scripts',()=>{
 for(const file of ['display-shared.js','display.js'])parse(source(file),{ecmaVersion:5});
 assert.doesNotMatch(source('display.html'),/type="module"/);
 assert.doesNotMatch(source('display.css').replace(/\/\*[\s\S]*?\*\//g,''),/var\(|\bgrid\b|\bdvh\b|clamp\(/i);
});
test('old browser pairs, renders agents together, and retries network failure without modern APIs',()=>{
 const dom=new JSDOM(source('display.html'),{url:'http://phone.test/display#pair=12345678',runScripts:'outside-only'});
 const w=dom.window, requests=[], timers=[];
 w.fetch=w.EventSource=w.Promise=w.Map=w.URLSearchParams=undefined;
 w.Element.prototype.append=w.Element.prototype.replaceChildren=undefined;
 w.setTimeout=fn=>{timers.push(fn);return timers.length;};w.clearTimeout=()=>{};
 w.XMLHttpRequest=function(){this.open=(method,path)=>{this.method=method;this.path=path;};this.setRequestHeader=()=>{};this.send=body=>{this.body=body;requests.push(this);};};
 const reply=(status,data)=>{const r=requests.shift();r.status=status;r.responseText=JSON.stringify(data);r.readyState=4;r.onreadystatechange();return r;};
 w.eval(source('display-shared.js'));w.eval(source('display.js'));
 assert.equal(w.document.getElementById('pair-code').value,'12345678');
 reply(401,{error:'unauthorized'});
 assert.notEqual(w.document.getElementById('pair-screen').style.display,'none');
 w.document.getElementById('pair-form').dispatchEvent(new w.Event('submit',{cancelable:true}));
 assert.equal(requests[0].path,'/api/pair');assert.equal(JSON.parse(requests[0].body).code,'12345678');
 reply(200,{id:'device'});
 const data={cards:[{pluginId:'agents',subtitle:'pi',pluginStatus:'running',status:'running'},{pluginId:'agents',subtitle:'Codex',pluginStatus:'running',status:'waiting'},{pluginId:'todo',title:'待办',type:'list',pluginStatus:'running',items:[{title:'<script>private</script>',done:false}]}],displayPlugins:[{id:'agents',status:'running'},{id:'todo',status:'running'},{id:'clock',name:'时钟',status:'starting'}]};
 reply(200,data);
 assert.equal(w.document.querySelectorAll('.card').length,3);
 assert.equal(w.document.querySelectorAll('.agent-overview').length,1);
 assert.equal(w.document.querySelectorAll('.agent-state').length,2);
 assert.match(w.document.getElementById('cards').textContent,/工作中/);
 assert.match(w.document.getElementById('cards').textContent,/等待你处理/);
 assert.equal(w.document.querySelectorAll('#cards script').length,0);
 for(const card of w.document.querySelectorAll('.card'))assert.match(card.style.height,/px$/);
 timers.pop()();requests.shift().onerror();
 assert.match(w.document.getElementById('connection').textContent,/离线/);
 assert.equal(w.document.querySelectorAll('.card').length,3);
 timers.pop()();reply(401,{error:'revoked'});
 assert.equal(w.document.querySelectorAll('.card').length,0);
 dom.window.close();
});
